name: Build and Release pip package

on:
  release:
    types: [published, prereleased]

permissions:
  packages: write
  contents: write

jobs:
  build:
    name: Build pip package
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout toolkit repository
      uses: actions/checkout@v4
      with:
        ref: main
        lfs: true

    - name: Create prebuilts directory
      run: mkdir -p pysynap/prebuilts

    - name: Checkout toolkit-prebuilts repository
      uses: actions/checkout@v4
      with:
        repository: synaptics-synap/toolkit-prebuilts
        ref: main
        path: pysynap/prebuilts
        lfs: true

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Add __init__.py to scripts and prebuilts directories
      run: |
        mkdir -p pysynap/scripts
        touch pysynap/scripts/__init__.py
        touch pysynap/prebuilts/__init__.py
      working-directory: ${{ github.workspace }}

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install build
          pip install --upgrade twine

    - name: Run build
      run: |
        python3 -m build

    - name: Get wheel file name
      run: echo "WHEEL_FILE=$(basename $(ls dist/*.whl))" >> $GITHUB_ENV

    - name: Upload wheel as asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/${{ env.WHEEL_FILE }}
        asset_name: ${{ env.WHEEL_FILE }}
        asset_content_type: application/zip